"""
constants.py
------------
Single source of truth for:
  - SKILL_ALIASES       : raw → canonical skill name mappings
  - ALL_SKILLS          : complete list of known canonical skills
  - JOB_ROLES           : all supported job role labels
  - ROLE_SKILL_MAP      : required + bonus skills per role (for gap analysis)
  - LEARNING_RESOURCES  : skill → learning resource URL map
"""

# ---------------------------------------------------------------------------
# Skill alias dictionary
# raw (lowercase) → canonical display name
# ---------------------------------------------------------------------------
SKILL_ALIASES: dict[str, str] = {
    # Python ecosystem
    "py": "Python",
    "python3": "Python",
    "python 3": "Python",
    "python2": "Python",

    # JavaScript / TypeScript
    "js": "JavaScript",
    "javascript": "JavaScript",
    "es6": "JavaScript",
    "ecmascript": "JavaScript",
    "ts": "TypeScript",
    "typescript": "TypeScript",

    # Web frameworks
    "reactjs": "React",
    "react.js": "React",
    "react js": "React",
    "vuejs": "Vue.js",
    "vue js": "Vue.js",
    "vue": "Vue.js",
    "angular": "Angular",
    "angularjs": "Angular",
    "nextjs": "Next.js",
    "next.js": "Next.js",
    "nodejs": "Node.js",
    "node js": "Node.js",
    "node": "Node.js",
    "expressjs": "Express.js",
    "express": "Express.js",
    "express.js": "Express.js",
    "django rest framework": "Django",
    "drf": "Django",
    "fastapi": "FastAPI",
    "flask": "Flask",
    "spring boot": "Spring Boot",
    "springboot": "Spring Boot",
    "spring": "Spring Boot",

    # Databases
    "postgresql": "PostgreSQL",
    "postgres": "PostgreSQL",
    "mysql": "MySQL",
    "mongodb": "MongoDB",
    "mongo": "MongoDB",
    "redis": "Redis",
    "sqlite": "SQLite",
    "mssql": "SQL Server",
    "microsoft sql server": "SQL Server",
    "sql server": "SQL Server",
    "cassandra": "Apache Cassandra",
    "elasticsearch": "Elasticsearch",
    "elastic search": "Elasticsearch",

    # Cloud
    "amazon web services": "AWS",
    "aws": "AWS",
    "google cloud platform": "GCP",
    "google cloud": "GCP",
    "gcp": "GCP",
    "microsoft azure": "Azure",
    "azure": "Azure",

    # DevOps / containers
    "docker": "Docker",
    "kubernetes": "Kubernetes",
    "k8s": "Kubernetes",
    "ci/cd": "CI/CD",
    "cicd": "CI/CD",
    "jenkins": "Jenkins",
    "github actions": "GitHub Actions",
    "gitlab ci": "GitLab CI",
    "terraform": "Terraform",
    "ansible": "Ansible",
    "linux": "Linux",
    "unix": "Linux",
    "bash": "Bash/Shell",
    "shell scripting": "Bash/Shell",
    "shell": "Bash/Shell",
    "git": "Git",
    "github": "Git",
    "gitlab": "Git",

    # ML / AI
    "machine learning": "Machine Learning",
    "ml": "Machine Learning",
    "mahchine learning": "Machine Learning",  # common typo
    "deep learning": "Deep Learning",
    "deep lerning": "Deep Learning",  # common typo
    "dl": "Deep Learning",
    "nlp": "NLP",
    "natural language processing": "NLP",
    "text preprocessing": "NLP",
    "text processing": "NLP",
    "computer vision": "Computer Vision",
    "cv": "Computer Vision",
    "tensorflow": "TensorFlow",
    "tf": "TensorFlow",
    "pytorch": "PyTorch",
    "torch": "PyTorch",
    "keras": "Keras",
    "scikit learn": "scikit-learn",
    "scikit-learn": "scikit-learn",
    "sklearn": "scikit-learn",
    "xgboost": "XGBoost",
    "lightgbm": "LightGBM",
    "hugging face": "Hugging Face",
    "huggingface": "Hugging Face",
    "langchain": "LangChain",
    "openai api": "OpenAI API",
    "openrouter": "OpenAI API",
    "llm": "LLMs",
    "llms": "LLMs",
    "large language models": "LLMs",
    "large language models (llms)": "LLMs",
    "generative ai": "Generative AI",
    "generative ai (genai)": "Generative AI",
    "genai": "Generative AI",
    "gen ai": "Generative AI",
    "rag": "RAG",
    "retrieval augmented generation": "RAG",
    "augmented generation (rag)": "RAG",
    "augmented generation": "RAG",

    # ML Algorithms & Techniques
    "logistic regression": "Logistic Regression",
    "linear regression": "Linear Regression",
    "random forest": "Random Forest",
    "decision tree": "Decision Trees",
    "decision trees": "Decision Trees",
    "knn": "KNN",
    "k-nearest neighbors": "KNN",
    "k nearest neighbors": "KNN",
    "svd": "SVD",
    "singular value decomposition": "SVD",
    "recommendation system": "Recommendation Systems",
    "recommendation systems": "Recommendation Systems",
    "recommendation system svd": "Recommendation Systems",
    "collaborative filtering": "Recommendation Systems",
    "svm": "SVM",
    "support vector machine": "SVM",
    "naive bayes": "Naive Bayes",
    "gradient boosting": "Gradient Boosting",
    "catboost": "CatBoost",
    "ensemble methods": "Ensemble Methods",
    "feature engineering": "Feature Engineering",
    "feature selection": "Feature Engineering",
    "hyperparameter tuning": "Hyperparameter Tuning",
    "model evaluation": "Model Evaluation",
    "cross validation": "Model Evaluation",
    "cross-validation": "Model Evaluation",

    # Deep Learning Architectures
    "rnn": "RNN",
    "recurrent neural network": "RNN",
    "recurrent neural networks": "RNN",
    "lstm": "LSTM",
    "long short-term memory": "LSTM",
    "long short term memory": "LSTM",
    "gru": "GRU",
    "gated recurrent unit": "GRU",
    "cnn": "CNN",
    "convolutional neural network": "CNN",
    "convolutional neural networks": "CNN",
    "transformer": "Transformers",
    "transformers": "Transformers",
    "attention mechanism": "Transformers",
    "bert": "BERT",
    "gpt": "GPT",
    "gan": "GANs",
    "gans": "GANs",
    "generative adversarial network": "GANs",
    "autoencoder": "Autoencoders",
    "autoencoders": "Autoencoders",
    "neural network": "Neural Networks",
    "neural networks": "Neural Networks",
    "ann": "Neural Networks",
    "mlflow": "MLflow",

    # Data
    "pandas": "Pandas",
    "numpy": "NumPy",
    "matplotlib": "Matplotlib",
    "seaborn": "Seaborn",
    "plotly": "Plotly",
    "tableau": "Tableau",
    "power bi": "Power BI",
    "powerbi": "Power BI",
    "excel": "Excel",
    "microsoft excel": "Excel",
    "advance excel": "Advanced Excel",
    "advanced excel": "Advanced Excel",
    "adavance excel": "Advanced Excel",  # common typo
    "spark": "Apache Spark",
    "apache spark": "Apache Spark",
    "pyspark": "Apache Spark",
    "hadoop": "Hadoop",
    "kafka": "Apache Kafka",
    "apache kafka": "Apache Kafka",
    "airflow": "Apache Airflow",
    "apache airflow": "Apache Airflow",
    "dbt": "dbt",
    "data build tool": "dbt",
    "snowflake": "Snowflake",
    "bigquery": "BigQuery",
    "google bigquery": "BigQuery",
    "redshift": "Amazon Redshift",
    "amazon redshift": "Amazon Redshift",

    # Data Analysis & Statistics
    "data handling": "Data Analysis",
    "data analysis": "Data Analysis",
    "data analytics": "Data Analysis",
    "data visualization": "Data Visualization",
    "data wrangling": "Data Wrangling",
    "data cleaning": "Data Wrangling",
    "data preprocessing": "Data Wrangling",
    "eda": "EDA",
    "exploratory data analysis": "EDA",
    "correlation analysis": "Statistical Analysis",
    "trend analysis": "Statistical Analysis",
    "outlier detection": "Anomaly Detection",
    "anomaly detection": "Anomaly Detection",
    "regression analysis": "Statistical Analysis",
    "statistical analysis": "Statistical Analysis",
    "statistics": "Statistics",
    "probability": "Statistics",
    "hypothesis testing": "Statistics",
    "a/b testing": "A/B Testing",
    "ab testing": "A/B Testing",
    "sql": "SQL",
    "structured query language": "SQL",
    "nosql": "NoSQL",
    "web scraping": "Web Scraping",
    "beautiful soup": "Web Scraping",
    "beautifulsoup": "Web Scraping",
    "scrapy": "Web Scraping",
    "scipy": "SciPy",
    "streamlit": "Streamlit",
    "jupyter": "Jupyter",
    "jupyter notebook": "Jupyter",
    "google colab": "Jupyter",

    # Mobile
    "react native": "React Native",
    "flutter": "Flutter",
    "dart": "Dart",
    "swift": "Swift",
    "swiftui": "SwiftUI",
    "kotlin": "Kotlin",
    "android": "Android",
    "android development": "Android",
    "android studio": "Android",
    "ios": "iOS",
    "ios development": "iOS",
    "objective c": "Objective-C",
    "objective-c": "Objective-C",
    "xcode": "Xcode",
    "firebase": "Firebase",
    "google firebase": "Firebase",
    "expo": "Expo",
    "cordova": "Apache Cordova",
    "ionic": "Ionic",
    "xamarin": "Xamarin",

    # Languages
    "java": "Java",
    "core java": "Java",
    "j2ee": "Java",
    "c": "C",
    "c programming": "C",
    "c language": "C",
    "c++": "C++",
    "cpp": "C++",
    "c#": "C#",
    "csharp": "C#",
    "c sharp": "C#",
    ".net": ".NET",
    "dotnet": ".NET",
    "asp.net": "ASP.NET",
    "asp net": "ASP.NET",
    "go": "Go",
    "golang": "Go",
    "rust": "Rust",
    "ruby": "Ruby",
    "ruby on rails": "Ruby on Rails",
    "rails": "Ruby on Rails",
    "php": "PHP",
    "laravel": "Laravel",
    "symfony": "Symfony",
    "wordpress": "WordPress",
    "scala": "Scala",
    "r": "R",
    "r language": "R",
    "r programming": "R",
    "matlab": "MATLAB",
    "perl": "Perl",
    "haskell": "Haskell",
    "elixir": "Elixir",
    "erlang": "Erlang",
    "lua": "Lua",
    "julia": "Julia",
    "solidity": "Solidity",
    "assembly": "Assembly",
    "cobol": "COBOL",
    "fortran": "Fortran",
    "vba": "VBA",
    "visual basic": "VBA",
    "powershell": "PowerShell",
    "html": "HTML/CSS",
    "css": "HTML/CSS",
    "html5": "HTML/CSS",
    "css3": "HTML/CSS",
    "html/css": "HTML/CSS",
    "html css": "HTML/CSS",
    "sass": "Sass/SCSS",
    "scss": "Sass/SCSS",
    "less": "LESS",
    "tailwind": "Tailwind CSS",
    "tailwindcss": "Tailwind CSS",
    "tailwind css": "Tailwind CSS",
    "bootstrap": "Bootstrap",
    "material ui": "Material UI",
    "materialui": "Material UI",
    "mui": "Material UI",
    "styled components": "Styled Components",
    "styled-components": "Styled Components",
    "chakra ui": "Chakra UI",

    # Web Frameworks & Libraries (additional)
    "svelte": "Svelte",
    "sveltekit": "SvelteKit",
    "nuxt": "Nuxt.js",
    "nuxt.js": "Nuxt.js",
    "nuxtjs": "Nuxt.js",
    "remix": "Remix",
    "gatsby": "Gatsby",
    "astro": "Astro",
    "jquery": "jQuery",
    "backbone": "Backbone.js",
    "ember": "Ember.js",
    "three.js": "Three.js",
    "threejs": "Three.js",
    "d3": "D3.js",
    "d3.js": "D3.js",
    "socket.io": "Socket.io",
    "socketio": "Socket.io",
    "prisma": "Prisma",
    "sequelize": "Sequelize",
    "mongoose": "Mongoose",
    "typeorm": "TypeORM",
    "drizzle": "Drizzle ORM",
    "webpack": "Webpack",
    "vite": "Vite",
    "parcel": "Parcel",
    "babel": "Babel",
    "eslint": "ESLint",
    "prettier": "Prettier",
    "storybook": "Storybook",
    "redux": "Redux",
    "zustand": "Zustand",
    "mobx": "MobX",
    "react query": "React Query",
    "tanstack query": "React Query",
    "swr": "SWR",
    "axios": "Axios",
    "pwa": "PWA",
    "progressive web app": "PWA",
    "service worker": "Service Workers",
    "web components": "Web Components",
    "webassembly": "WebAssembly",
    "wasm": "WebAssembly",

    # Databases (additional)
    "mariadb": "MariaDB",
    "oracle": "Oracle DB",
    "oracle db": "Oracle DB",
    "oracle database": "Oracle DB",
    "couchdb": "CouchDB",
    "dynamodb": "DynamoDB",
    "amazon dynamodb": "DynamoDB",
    "neo4j": "Neo4j",
    "graph database": "Neo4j",
    "influxdb": "InfluxDB",
    "timescaledb": "TimescaleDB",
    "cockroachdb": "CockroachDB",
    "supabase": "Supabase",
    "firebase firestore": "Firestore",
    "firestore": "Firestore",
    "realm": "Realm",
    "memcached": "Memcached",
    "etcd": "etcd",
    "amazon rds": "Amazon RDS",
    "rds": "Amazon RDS",
    "amazon s3": "AWS S3",
    "aws s3": "AWS S3",
    "s3": "AWS S3",
    "plsql": "PL/SQL",
    "pl/sql": "PL/SQL",
    "t-sql": "T-SQL",
    "tsql": "T-SQL",
    "stored procedures": "Stored Procedures",
    "database design": "Database Design",
    "database management": "Database Design",
    "data modeling": "Data Modeling",
    "er diagram": "Data Modeling",
    "normalization": "Data Modeling",

    # Architecture / Design
    "microservices": "Microservices",
    "micro services": "Microservices",
    "microservices architecture": "Microservices",
    "monolithic": "Monolithic Architecture",
    "serverless": "Serverless",
    "serverless architecture": "Serverless",
    "event driven": "Event-Driven Architecture",
    "event-driven architecture": "Event-Driven Architecture",
    "message queue": "Message Queues",
    "message queues": "Message Queues",
    "rabbitmq": "RabbitMQ",
    "rest api": "REST APIs",
    "restful api": "REST APIs",
    "rest apis": "REST APIs",
    "restful": "REST APIs",
    "rest": "REST APIs",
    "api development": "REST APIs",
    "api design": "API Design",
    "api gateway": "API Gateway",
    "graphql": "GraphQL",
    "grpc": "gRPC",
    "websocket": "WebSockets",
    "websockets": "WebSockets",
    "oauth": "OAuth",
    "oauth2": "OAuth",
    "jwt": "JWT",
    "json web token": "JWT",
    "saml": "SAML",
    "sso": "SSO",
    "single sign-on": "SSO",
    "design patterns": "Design Patterns",
    "solid principles": "SOLID Principles",
    "solid": "SOLID Principles",
    "oop": "OOP",
    "object oriented programming": "OOP",
    "object-oriented programming": "OOP",
    "functional programming": "Functional Programming",
    "mvc": "MVC",
    "mvvm": "MVVM",
    "clean architecture": "Clean Architecture",
    "domain driven design": "Domain-Driven Design",
    "ddd": "Domain-Driven Design",
    "system design": "System Design",
    "low level design": "System Design",
    "high level design": "System Design",
    "scalability": "System Design",
    "distributed systems": "Distributed Systems",
    "caching": "Caching",
    "load balancing": "Load Balancing",
    "cdn": "CDN",
    "content delivery network": "CDN",

    # Cloud (additional)
    "aws lambda": "AWS Lambda",
    "lambda": "AWS Lambda",
    "ec2": "AWS EC2",
    "aws ec2": "AWS EC2",
    "ecs": "AWS ECS",
    "aws ecs": "AWS ECS",
    "eks": "AWS EKS",
    "aws eks": "AWS EKS",
    "fargate": "AWS Fargate",
    "cloudformation": "CloudFormation",
    "aws cloudformation": "CloudFormation",
    "cloudwatch": "CloudWatch",
    "aws cloudwatch": "CloudWatch",
    "sqs": "AWS SQS",
    "sns": "AWS SNS",
    "route53": "Route 53",
    "iam": "AWS IAM",
    "vpc": "VPC",
    "google kubernetes engine": "GKE",
    "gke": "GKE",
    "cloud functions": "Cloud Functions",
    "google cloud functions": "Cloud Functions",
    "cloud run": "Cloud Run",
    "app engine": "App Engine",
    "azure devops": "Azure DevOps",
    "azure functions": "Azure Functions",
    "azure kubernetes service": "AKS",
    "aks": "AKS",
    "azure blob storage": "Azure Blob Storage",
    "digitalocean": "DigitalOcean",
    "heroku": "Heroku",
    "netlify": "Netlify",
    "vercel": "Vercel",
    "render": "Render",
    "fly.io": "Fly.io",
    "linode": "Linode",
    "openstack": "OpenStack",
    "cloud computing": "Cloud Computing",
    "iaas": "Cloud Computing",
    "paas": "Cloud Computing",
    "saas": "SaaS",

    # DevOps & CI/CD (additional)
    "docker compose": "Docker Compose",
    "docker-compose": "Docker Compose",
    "docker swarm": "Docker Swarm",
    "containerd": "Containerd",
    "podman": "Podman",
    "helm": "Helm",
    "helm charts": "Helm",
    "istio": "Istio",
    "service mesh": "Service Mesh",
    "envoy": "Envoy",
    "nginx": "Nginx",
    "apache": "Apache HTTP",
    "apache http": "Apache HTTP",
    "traefik": "Traefik",
    "haproxy": "HAProxy",
    "argocd": "ArgoCD",
    "argo cd": "ArgoCD",
    "fluxcd": "FluxCD",
    "spinnaker": "Spinnaker",
    "circleci": "CircleCI",
    "circle ci": "CircleCI",
    "travis ci": "Travis CI",
    "travisci": "Travis CI",
    "bamboo": "Bamboo",
    "teamcity": "TeamCity",
    "azure pipelines": "Azure Pipelines",
    "bitbucket pipelines": "Bitbucket Pipelines",
    "drone ci": "Drone CI",
    "prometheus": "Prometheus",
    "grafana": "Grafana",
    "datadog": "Datadog",
    "new relic": "New Relic",
    "newrelic": "New Relic",
    "splunk": "Splunk",
    "elk stack": "ELK Stack",
    "elk": "ELK Stack",
    "logstash": "Logstash",
    "kibana": "Kibana",
    "fluentd": "Fluentd",
    "jaeger": "Jaeger",
    "opentelemetry": "OpenTelemetry",
    "pagerduty": "PagerDuty",
    "nagios": "Nagios",
    "zabbix": "Zabbix",
    "vagrant": "Vagrant",
    "packer": "Packer",
    "pulumi": "Pulumi",
    "chef": "Chef",
    "puppet": "Puppet",
    "saltstack": "SaltStack",
    "infrastructure as code": "Infrastructure as Code",
    "iac": "Infrastructure as Code",
    "gitops": "GitOps",
    "site reliability engineering": "SRE",
    "sre": "SRE",
    "devops": "DevOps",
    "devsecops": "DevSecOps",
    "continuous integration": "CI/CD",
    "continuous deployment": "CI/CD",
    "continuous delivery": "CI/CD",

    # Testing (expanded)
    "unit testing": "Unit Testing",
    "integration testing": "Integration Testing",
    "e2e testing": "E2E Testing",
    "end to end testing": "E2E Testing",
    "end-to-end testing": "E2E Testing",
    "tdd": "TDD",
    "test driven development": "TDD",
    "test-driven development": "TDD",
    "bdd": "BDD",
    "behavior driven development": "BDD",
    "pytest": "pytest",
    "unittest": "pytest",
    "jest": "Jest",
    "mocha": "Mocha",
    "chai": "Chai",
    "jasmine": "Jasmine",
    "karma": "Karma",
    "enzyme": "Enzyme",
    "react testing library": "React Testing Library",
    "testing library": "React Testing Library",
    "selenium": "Selenium",
    "cypress": "Cypress",
    "playwright": "Playwright",
    "puppeteer": "Puppeteer",
    "appium": "Appium",
    "postman": "Postman",
    "insomnia": "Insomnia",
    "swagger": "Swagger/OpenAPI",
    "openapi": "Swagger/OpenAPI",
    "jmeter": "JMeter",
    "locust": "Locust",
    "k6": "k6",
    "load testing": "Load Testing",
    "performance testing": "Performance Testing",
    "qa": "QA",
    "quality assurance": "QA",
    "manual testing": "Manual Testing",
    "automation testing": "Test Automation",
    "test automation": "Test Automation",
    "automated testing": "Test Automation",
    "sonarqube": "SonarQube",
    "code review": "Code Review",
    "debugging": "Debugging",

    # Security
    "cybersecurity": "Cybersecurity",
    "cyber security": "Cybersecurity",
    "information security": "Cybersecurity",
    "infosec": "Cybersecurity",
    "network security": "Network Security",
    "application security": "Application Security",
    "appsec": "Application Security",
    "owasp": "OWASP",
    "penetration testing": "Penetration Testing",
    "pen testing": "Penetration Testing",
    "pentesting": "Penetration Testing",
    "ethical hacking": "Ethical Hacking",
    "vulnerability assessment": "Vulnerability Assessment",
    "siem": "SIEM",
    "intrusion detection": "IDS/IPS",
    "ids": "IDS/IPS",
    "ips": "IDS/IPS",
    "firewall": "Firewall Management",
    "encryption": "Encryption",
    "ssl": "SSL/TLS",
    "tls": "SSL/TLS",
    "ssl/tls": "SSL/TLS",
    "https": "SSL/TLS",
    "cryptography": "Cryptography",
    "hashicorp vault": "HashiCorp Vault",
    "vault": "HashiCorp Vault",
    "kms": "KMS",
    "identity management": "Identity Management",
    "ldap": "LDAP",
    "active directory": "Active Directory",
    "rbac": "RBAC",
    "zero trust": "Zero Trust",
    "compliance": "Compliance",
    "gdpr": "GDPR",
    "hipaa": "HIPAA",
    "soc2": "SOC 2",
    "soc 2": "SOC 2",
    "iso 27001": "ISO 27001",

    # Networking
    "tcp/ip": "TCP/IP",
    "tcp ip": "TCP/IP",
    "dns": "DNS",
    "dhcp": "DHCP",
    "http": "HTTP",
    "http/https": "HTTP",
    "networking": "Networking",
    "computer networks": "Networking",
    "computer networking": "Networking",
    "network protocols": "Networking",
    "vpn": "VPN",
    "proxy": "Proxy",
    "reverse proxy": "Reverse Proxy",
    "ssh": "SSH",
    "ftp": "FTP",
    "smtp": "SMTP",
    "mqtt": "MQTT",
    "amqp": "AMQP",

    # Design & UI/UX
    "figma": "Figma",
    "sketch": "Sketch",
    "adobe xd": "Adobe XD",
    "invision": "InVision",
    "zeplin": "Zeplin",
    "photoshop": "Photoshop",
    "adobe photoshop": "Photoshop",
    "illustrator": "Illustrator",
    "adobe illustrator": "Illustrator",
    "after effects": "After Effects",
    "premiere pro": "Premiere Pro",
    "canva": "Canva",
    "ui design": "UI/UX Design",
    "ux design": "UI/UX Design",
    "ui/ux": "UI/UX Design",
    "ui ux": "UI/UX Design",
    "user interface": "UI/UX Design",
    "user experience": "UI/UX Design",
    "wireframing": "Wireframing",
    "prototyping": "Prototyping",
    "responsive design": "Responsive Design",
    "responsive web design": "Responsive Design",
    "accessibility": "Web Accessibility",
    "wcag": "Web Accessibility",
    "a11y": "Web Accessibility",

    # Project Management & Methodologies
    "agile": "Agile",
    "agile methodology": "Agile",
    "agile methodologies": "Agile",
    "scrum": "Scrum",
    "scrum master": "Scrum",
    "kanban": "Kanban",
    "lean": "Lean",
    "waterfall": "Waterfall",
    "jira": "Jira",
    "confluence": "Confluence",
    "trello": "Trello",
    "asana": "Asana",
    "notion": "Notion",
    "monday.com": "Monday.com",
    "basecamp": "Basecamp",
    "slack": "Slack",
    "microsoft teams": "Microsoft Teams",
    "teams": "Microsoft Teams",
    "project management": "Project Management",
    "product management": "Product Management",
    "stakeholder management": "Stakeholder Management",
    "requirement analysis": "Requirements Analysis",
    "requirements gathering": "Requirements Analysis",
    "sdlc": "SDLC",
    "software development life cycle": "SDLC",

    # Version Control & Collaboration
    "git": "Git",
    "github": "GitHub",
    "gitlab": "GitLab",
    "bitbucket": "Bitbucket",
    "svn": "SVN",
    "subversion": "SVN",
    "mercurial": "Mercurial",
    "version control": "Version Control",

    # Blockchain & Web3
    "blockchain": "Blockchain",
    "ethereum": "Ethereum",
    "smart contracts": "Smart Contracts",
    "smart contract": "Smart Contracts",
    "web3": "Web3",
    "web3.js": "Web3",
    "ethers.js": "Ethers.js",
    "hardhat": "Hardhat",
    "truffle": "Truffle",
    "defi": "DeFi",
    "nft": "NFT",
    "ipfs": "IPFS",
    "hyperledger": "Hyperledger",

    # IoT & Embedded
    "iot": "IoT",
    "internet of things": "IoT",
    "raspberry pi": "Raspberry Pi",
    "arduino": "Arduino",
    "embedded systems": "Embedded Systems",
    "embedded c": "Embedded C",
    "rtos": "RTOS",
    "fpga": "FPGA",
    "verilog": "Verilog",
    "vhdl": "VHDL",

    # Game Development
    "unity": "Unity",
    "unity3d": "Unity",
    "unreal engine": "Unreal Engine",
    "unreal": "Unreal Engine",
    "godot": "Godot",
    "game development": "Game Development",
    "opengl": "OpenGL",
    "vulkan": "Vulkan",
    "directx": "DirectX",

    # Data Formats & Protocols
    "json": "JSON",
    "xml": "XML",
    "yaml": "YAML",
    "csv": "CSV",
    "protobuf": "Protocol Buffers",
    "protocol buffers": "Protocol Buffers",
    "avro": "Apache Avro",
    "parquet": "Parquet",

    # Soft Skills & Other
    "problem solving": "Problem Solving",
    "problem-solving": "Problem Solving",
    "critical thinking": "Critical Thinking",
    "communication": "Communication",
    "communication skills": "Communication",
    "teamwork": "Teamwork",
    "team work": "Teamwork",
    "collaboration": "Teamwork",
    "leadership": "Leadership",
    "time management": "Time Management",
    "presentation": "Presentation Skills",
    "presentation skills": "Presentation Skills",
    "public speaking": "Public Speaking",
    "technical writing": "Technical Writing",
    "documentation": "Documentation",
    "research": "Research",
    "analytical skills": "Analytical Skills",
    "analytical thinking": "Analytical Skills",
    "data structures": "Data Structures",
    "data structures and algorithms": "DSA",
    "dsa": "DSA",
    "algorithms": "Algorithms",
    "competitive programming": "Competitive Programming",
    "cp": "Competitive Programming",
    "leetcode": "Competitive Programming",
    "operating systems": "Operating Systems",
    "os": "Operating Systems",
    "windows": "Windows",
    "macos": "macOS",
    "dbms": "DBMS",
    "rdbms": "DBMS",
    "data structures \u0026 algorithms": "DSA",
    "oops": "OOP",
    "computer science": "Computer Science",
}

# ---------------------------------------------------------------------------
# All known canonical skills (used to build the feature vector)
# ---------------------------------------------------------------------------
ALL_SKILLS: list[str] = sorted(set(SKILL_ALIASES.values()))

# ---------------------------------------------------------------------------
# Supported job roles
# ---------------------------------------------------------------------------
JOB_ROLES: list[str] = [
    "Backend Developer",
    "Frontend Developer",
    "Full Stack Developer",
    "Data Scientist",
    "Machine Learning Engineer",
    "DevOps Engineer",
    "Cloud Engineer",
    "Data Engineer",
    "Mobile Developer",
    "AI/LLM Engineer",
]

# ---------------------------------------------------------------------------
# Role → skill mapping for gap analysis
# Format: { "role": { "required": [...], "bonus": [...] } }
# ---------------------------------------------------------------------------
ROLE_SKILL_MAP: dict[str, dict[str, list[str]]] = {
    "Backend Developer": {
        "required": ["Python", "Java", "Node.js", "REST APIs", "PostgreSQL", "Git"],
        "bonus":    ["Docker", "Redis", "Kubernetes", "Microservices", "CI/CD", "AWS"],
    },
    "Frontend Developer": {
        "required": ["JavaScript", "React", "HTML", "CSS", "Git"],
        "bonus":    ["TypeScript", "Next.js", "Vue.js", "GraphQL", "Jest", "Cypress"],
    },
    "Full Stack Developer": {
        "required": ["JavaScript", "React", "Node.js", "REST APIs", "PostgreSQL", "Git"],
        "bonus":    ["TypeScript", "Docker", "AWS", "GraphQL", "Redis", "CI/CD"],
    },
    "Data Scientist": {
        "required": ["Python", "Machine Learning", "Pandas", "NumPy", "scikit-learn", "SQL"],
        "bonus":    ["Deep Learning", "TensorFlow", "PyTorch", "Tableau", "Power BI", "Apache Spark"],
    },
    "Machine Learning Engineer": {
        "required": ["Python", "Machine Learning", "Deep Learning", "TensorFlow", "scikit-learn", "Docker"],
        "bonus":    ["PyTorch", "Kubernetes", "MLflow", "Apache Spark", "AWS", "NLP"],
    },
    "DevOps Engineer": {
        "required": ["Docker", "Kubernetes", "CI/CD", "Linux", "Git", "Bash/Shell"],
        "bonus":    ["Terraform", "Ansible", "AWS", "Jenkins", "Python", "Monitoring"],
    },
    "Cloud Engineer": {
        "required": ["AWS", "Docker", "Kubernetes", "Terraform", "Linux", "CI/CD"],
        "bonus":    ["Azure", "GCP", "Python", "Ansible", "Security", "Networking"],
    },
    "Data Engineer": {
        "required": ["Python", "Apache Spark", "Apache Airflow", "SQL", "dbt", "PostgreSQL"],
        "bonus":    ["Snowflake", "BigQuery", "Apache Kafka", "AWS", "Docker", "Hadoop"],
    },
    "Mobile Developer": {
        "required": ["React Native", "JavaScript", "Git"],
        "bonus":    ["Flutter", "Swift", "Kotlin", "iOS", "Android", "Firebase"],
    },
    "AI/LLM Engineer": {
        "required": ["Python", "LLMs", "NLP", "Hugging Face", "REST APIs", "Git"],
        "bonus":    ["LangChain", "RAG", "OpenAI API", "Generative AI", "Docker", "FastAPI"],
    },
}

# ---------------------------------------------------------------------------
# Learning resources for skill gap recommendations
# ---------------------------------------------------------------------------
LEARNING_RESOURCES: dict[str, dict[str, str]] = {
    "Python":           {"platform": "freeCodeCamp",  "url": "https://www.freecodecamp.org/learn/scientific-computing-with-python/"},
    "JavaScript":       {"platform": "MDN Web Docs",  "url": "https://developer.mozilla.org/en-US/docs/Learn/JavaScript"},
    "React":            {"platform": "React Docs",    "url": "https://react.dev/learn"},
    "Node.js":          {"platform": "Node.js Docs",  "url": "https://nodejs.org/en/learn"},
    "Docker":           {"platform": "Docker Docs",   "url": "https://docs.docker.com/get-started/"},
    "Kubernetes":       {"platform": "Kubernetes",    "url": "https://kubernetes.io/docs/tutorials/"},
    "AWS":              {"platform": "AWS Training",  "url": "https://aws.amazon.com/training/"},
    "GCP":              {"platform": "Google Cloud",  "url": "https://cloud.google.com/training"},
    "Azure":            {"platform": "Microsoft Learn","url": "https://learn.microsoft.com/en-us/training/azure/"},
    "Machine Learning": {"platform": "Coursera",      "url": "https://www.coursera.org/learn/machine-learning"},
    "Deep Learning":    {"platform": "fast.ai",       "url": "https://www.fast.ai/"},
    "TensorFlow":       {"platform": "TensorFlow",    "url": "https://www.tensorflow.org/tutorials"},
    "PyTorch":          {"platform": "PyTorch",       "url": "https://pytorch.org/tutorials/"},
    "scikit-learn":     {"platform": "scikit-learn",  "url": "https://scikit-learn.org/stable/tutorial/"},
    "PostgreSQL":       {"platform": "PostgreSQL Tutorial","url": "https://www.postgresqltutorial.com/"},
    "MongoDB":          {"platform": "MongoDB University","url": "https://university.mongodb.com/"},
    "Apache Spark":     {"platform": "Databricks",    "url": "https://www.databricks.com/learn/training"},
    "Apache Airflow":   {"platform": "Airflow Docs",  "url": "https://airflow.apache.org/docs/"},
    "Terraform":        {"platform": "HashiCorp Learn","url": "https://developer.hashicorp.com/terraform/tutorials"},
    "CI/CD":            {"platform": "GitHub Actions","url": "https://docs.github.com/en/actions"},
    "TypeScript":       {"platform": "TypeScript Docs","url": "https://www.typescriptlang.org/docs/"},
    "GraphQL":          {"platform": "GraphQL",       "url": "https://graphql.org/learn/"},
    "NLP":              {"platform": "Hugging Face",  "url": "https://huggingface.co/learn/nlp-course/"},
    "LLMs":             {"platform": "Andrej Karpathy","url": "https://www.youtube.com/watch?v=kCc8FmEb1nY"},
    "LangChain":        {"platform": "LangChain Docs","url": "https://python.langchain.com/docs/"},
    "React Native":     {"platform": "React Native",  "url": "https://reactnative.dev/docs/getting-started"},
    "Flutter":          {"platform": "Flutter Docs",  "url": "https://docs.flutter.dev/get-started"},
    "dbt":              {"platform": "dbt Learn",     "url": "https://courses.getdbt.com/"},
    "Snowflake":        {"platform": "Snowflake University","url": "https://www.snowflake.com/en/data-cloud/education/"},
    "Power BI":         {"platform": "Microsoft Learn","url": "https://learn.microsoft.com/en-us/power-bi/"},
    "Tableau":          {"platform": "Tableau Public","url": "https://public.tableau.com/en-us/s/resources"},
}

# ---------------------------------------------------------------------------
# Career path progression map  (used by career_path.py)
# ---------------------------------------------------------------------------
CAREER_PROGRESSION: dict[str, list[str]] = {
    "Backend Developer":         ["Senior Backend Developer", "Tech Lead", "Software Architect"],
    "Frontend Developer":        ["Senior Frontend Developer", "UI Lead", "Full Stack Developer"],
    "Full Stack Developer":      ["Senior Full Stack Developer", "Tech Lead", "Engineering Manager"],
    "Data Scientist":            ["Senior Data Scientist", "Lead Data Scientist", "Chief Data Officer"],
    "Machine Learning Engineer": ["Senior ML Engineer", "ML Tech Lead", "AI Research Scientist"],
    "DevOps Engineer":           ["Senior DevOps Engineer", "DevOps Lead", "Platform Engineer"],
    "Cloud Engineer":            ["Senior Cloud Engineer", "Cloud Architect", "Solutions Architect"],
    "Data Engineer":             ["Senior Data Engineer", "Data Architect", "Data Platform Lead"],
    "Mobile Developer":          ["Senior Mobile Developer", "Mobile Tech Lead", "Mobile Architect"],
    "AI/LLM Engineer":           ["Senior AI Engineer", "AI Research Engineer", "Head of AI"],
}

# Aliases for compatibility
CAREER_PATHS = CAREER_PROGRESSION
ROLE_REQUIRED_SKILLS = ROLE_SKILL_MAP

ROLE_DESCRIPTIONS: dict[str, str] = {
    "Senior Backend Developer": "Design and optimize scalable backend architectures.",
    "Tech Lead": "Lead technical decisions and mentor engineering teams.",
    "Software Architect": "Define high-level architecture and technology stack.",
    "Senior Frontend Developer": "Build advanced UI/UX and optimize frontend performance.",
    "UI Lead": "Lead UI development and design system implementation.",
    "Senior Full Stack Developer": "Architect both frontend and backend enterprise solutions.",
    "Engineering Manager": "Manage engineering teams and product delivery.",
    "Senior Data Scientist": "Develop advanced predictive models and analytics.",
    "Lead Data Scientist": "Lead data science projects and strategy.",
    "Chief Data Officer": "Drive organizational data strategy and innovation.",
    "Senior ML Engineer": "Deploy and scale machine learning models in production.",
    "ML Tech Lead": "Lead ML infrastructure and algorithmic design.",
    "AI Research Scientist": "Conduct cutting-edge AI research and innovation.",
    "Senior DevOps Engineer": "Optimize CI/CD and infrastructure automation.",
    "DevOps Lead": "Lead cloud infrastructure and DevOps practices.",
    "Platform Engineer": "Build internal developer platforms and tooling.",
    "Senior Cloud Engineer": "Design resilient and scalable cloud platforms.",
    "Cloud Architect": "Architect enterprise cloud solutions across providers.",
    "Solutions Architect": "Design comprehensive technical solutions for clients.",
    "Senior Data Engineer": "Build scalable data pipelines and warehouses.",
    "Data Architect": "Design enterprise data architecture and strategy.",
    "Data Platform Lead": "Lead data engineering and platform teams.",
    "Senior Mobile Developer": "Build complex cross-platform mobile applications.",
    "Mobile Tech Lead": "Lead mobile app development and architecture.",
    "Mobile Architect": "Design scalable mobile architectures and ecosystems.",
    "Senior AI Engineer": "Build production-ready LLM and generative AI applications.",
    "AI Research Engineer": "Research and implement innovative AI architectures.",
    "Head of AI": "Lead the organization's AI vision and strategy.",
}

ROLE_SALARY_RANGES: dict[str, dict[str, int]] = {
    "Senior Backend Developer": {"min": 1500000, "max": 3500000},
    "Tech Lead": {"min": 2500000, "max": 5000000},
    "Software Architect": {"min": 3500000, "max": 7000000},
    "Senior Frontend Developer": {"min": 1500000, "max": 3000000},
    "UI Lead": {"min": 2500000, "max": 4500000},
    "Senior Full Stack Developer": {"min": 1800000, "max": 4000000},
    "Engineering Manager": {"min": 3500000, "max": 8000000},
    "Senior Data Scientist": {"min": 1800000, "max": 4000000},
    "Lead Data Scientist": {"min": 3000000, "max": 6000000},
    "Chief Data Officer": {"min": 5000000, "max": 12000000},
    "Senior ML Engineer": {"min": 2000000, "max": 4500000},
    "ML Tech Lead": {"min": 3500000, "max": 7000000},
    "AI Research Scientist": {"min": 4000000, "max": 8000000},
    "Senior DevOps Engineer": {"min": 1800000, "max": 4000000},
    "DevOps Lead": {"min": 3000000, "max": 6000000},
    "Platform Engineer": {"min": 2500000, "max": 5000000},
    "Senior Cloud Engineer": {"min": 2000000, "max": 4500000},
    "Cloud Architect": {"min": 3500000, "max": 7000000},
    "Solutions Architect": {"min": 4000000, "max": 8000000},
    "Senior Data Engineer": {"min": 1800000, "max": 4000000},
    "Data Architect": {"min": 3500000, "max": 7000000},
    "Data Platform Lead": {"min": 4000000, "max": 8000000},
    "Senior Mobile Developer": {"min": 1500000, "max": 3500000},
    "Mobile Tech Lead": {"min": 2500000, "max": 5000000},
    "Mobile Architect": {"min": 3500000, "max": 7000000},
    "Senior AI Engineer": {"min": 2500000, "max": 5500000},
    "AI Research Engineer": {"min": 3500000, "max": 8000000},
    "Head of AI": {"min": 6000000, "max": 15000000},
}


# ---------------------------------------------------------------------------
# Project Suggestions — role-specific project ideas for Resume Coach
# ---------------------------------------------------------------------------
PROJECT_SUGGESTIONS: dict[str, list[dict]] = {
    "Backend Developer": [
        {"title": "RESTful E-Commerce API", "description": "Build a full REST API for an e-commerce platform with authentication, product catalog, cart, and order management using FastAPI/Django.", "tech_stack": ["Python", "FastAPI", "PostgreSQL", "Redis", "Docker"], "difficulty": "Intermediate", "time_weeks": 3},
        {"title": "Real-Time Chat Server", "description": "Create a WebSocket-based chat application with channels, direct messages, and message persistence.", "tech_stack": ["Node.js", "WebSockets", "MongoDB", "Redis"], "difficulty": "Intermediate", "time_weeks": 2},
        {"title": "URL Shortener with Analytics", "description": "Build a URL shortener service with click analytics, rate limiting, and caching for high throughput.", "tech_stack": ["Python", "Flask", "Redis", "PostgreSQL", "Docker"], "difficulty": "Beginner", "time_weeks": 1},
        {"title": "Microservices Blog Platform", "description": "Design a blog platform using microservices architecture with separate services for users, posts, comments, and notifications.", "tech_stack": ["Python", "FastAPI", "Docker", "RabbitMQ", "PostgreSQL"], "difficulty": "Advanced", "time_weeks": 5},
        {"title": "Task Queue System", "description": "Build a distributed task queue with worker processes, retry logic, scheduled tasks, and a dashboard.", "tech_stack": ["Python", "Celery", "Redis", "FastAPI", "Docker"], "difficulty": "Advanced", "time_weeks": 4},
    ],
    "Frontend Developer": [
        {"title": "Interactive Dashboard Builder", "description": "Build a drag-and-drop dashboard with customizable widgets, charts, and real-time data visualization.", "tech_stack": ["React", "TypeScript", "D3.js", "REST APIs"], "difficulty": "Advanced", "time_weeks": 4},
        {"title": "Social Media Feed Clone", "description": "Create an Instagram/Twitter-like feed with infinite scroll, image uploads, likes, comments, and real-time updates.", "tech_stack": ["React", "Next.js", "TypeScript", "CSS Modules"], "difficulty": "Intermediate", "time_weeks": 3},
        {"title": "Portfolio Website with CMS", "description": "Build a personal portfolio with a custom headless CMS for managing projects, blog posts, and testimonials.", "tech_stack": ["React", "Next.js", "TypeScript", "Markdown"], "difficulty": "Beginner", "time_weeks": 2},
        {"title": "Kanban Board App", "description": "Create a Trello-like project management board with drag-and-drop columns, task assignments, and filters.", "tech_stack": ["React", "TypeScript", "DnD Kit", "REST APIs"], "difficulty": "Intermediate", "time_weeks": 2},
        {"title": "Real-Time Collaborative Editor", "description": "Build a Google Docs-like collaborative text editor with real-time syncing and version history.", "tech_stack": ["React", "TypeScript", "WebSockets", "Yjs"], "difficulty": "Advanced", "time_weeks": 5},
    ],
    "Full Stack Developer": [
        {"title": "Project Management Tool", "description": "Build a full-stack Jira-like project management tool with sprints, kanban boards, and team collaboration.", "tech_stack": ["React", "Node.js", "PostgreSQL", "Docker", "TypeScript"], "difficulty": "Advanced", "time_weeks": 5},
        {"title": "Video Streaming Platform", "description": "Create a YouTube-like platform with video upload, transcoding, streaming, comments, and recommendations.", "tech_stack": ["React", "Node.js", "MongoDB", "AWS S3", "FFmpeg"], "difficulty": "Advanced", "time_weeks": 6},
        {"title": "Online Learning Platform", "description": "Build an LMS with course creation, video lessons, quizzes, progress tracking, and certificate generation.", "tech_stack": ["React", "Node.js", "PostgreSQL", "Stripe", "Docker"], "difficulty": "Intermediate", "time_weeks": 4},
        {"title": "Multi-Vendor Marketplace", "description": "Create a marketplace where vendors can list products, manage inventory, and handle order fulfillment.", "tech_stack": ["Next.js", "Node.js", "PostgreSQL", "Stripe", "Redis"], "difficulty": "Advanced", "time_weeks": 5},
    ],
    "Data Scientist": [
        {"title": "Customer Churn Predictor", "description": "Build an end-to-end ML pipeline to predict customer churn using telco/SaaS data with a Streamlit dashboard.", "tech_stack": ["Python", "scikit-learn", "Pandas", "Streamlit", "XGBoost"], "difficulty": "Intermediate", "time_weeks": 2},
        {"title": "Sentiment Analysis Pipeline", "description": "Create an NLP pipeline for social media sentiment analysis with data collection, cleaning, modeling, and visualization.", "tech_stack": ["Python", "NLP", "BERT", "Pandas", "Matplotlib"], "difficulty": "Intermediate", "time_weeks": 3},
        {"title": "Recommendation Engine", "description": "Build a collaborative filtering + content-based hybrid recommendation system for movies or products.", "tech_stack": ["Python", "scikit-learn", "Pandas", "NumPy", "Flask"], "difficulty": "Intermediate", "time_weeks": 3},
        {"title": "Time Series Forecasting Dashboard", "description": "Create a stock price / demand forecasting system using ARIMA, Prophet, and LSTM with interactive Plotly charts.", "tech_stack": ["Python", "Prophet", "TensorFlow", "Plotly", "Pandas"], "difficulty": "Advanced", "time_weeks": 4},
        {"title": "A/B Testing Framework", "description": "Design a statistical A/B testing framework with sample size calculators, significance tests, and result visualization.", "tech_stack": ["Python", "SciPy", "Pandas", "Streamlit", "SQL"], "difficulty": "Intermediate", "time_weeks": 2},
    ],
    "Machine Learning Engineer": [
        {"title": "ML Model Deployment Pipeline", "description": "Build an end-to-end ML pipeline with model training, versioning, containerized serving, and monitoring.", "tech_stack": ["Python", "Docker", "FastAPI", "MLflow", "scikit-learn"], "difficulty": "Advanced", "time_weeks": 4},
        {"title": "Image Classification API", "description": "Train a CNN for image classification and deploy it as a REST API with confidence scores and batch processing.", "tech_stack": ["Python", "PyTorch", "FastAPI", "Docker", "AWS"], "difficulty": "Intermediate", "time_weeks": 3},
        {"title": "Object Detection System", "description": "Build a real-time object detection system using YOLO with a web interface for image/video upload.", "tech_stack": ["Python", "PyTorch", "YOLO", "OpenCV", "FastAPI"], "difficulty": "Advanced", "time_weeks": 4},
        {"title": "Feature Store Implementation", "description": "Design and build a feature store for ML pipelines with feature versioning, serving, and monitoring.", "tech_stack": ["Python", "Redis", "PostgreSQL", "Docker", "Apache Spark"], "difficulty": "Advanced", "time_weeks": 5},
    ],
    "Data Engineer": [
        {"title": "ETL Pipeline with Airflow", "description": "Design a data pipeline to extract from APIs, transform with Spark, and load into a data warehouse on a schedule.", "tech_stack": ["Python", "Apache Airflow", "Apache Spark", "PostgreSQL", "Docker"], "difficulty": "Intermediate", "time_weeks": 3},
        {"title": "Real-Time Data Streaming", "description": "Build a streaming data pipeline with Kafka for ingesting and processing events in real-time.", "tech_stack": ["Python", "Apache Kafka", "Apache Spark", "Docker", "PostgreSQL"], "difficulty": "Advanced", "time_weeks": 4},
        {"title": "Data Lake Architecture", "description": "Design a data lake on AWS S3 with schema evolution, partitioning, and query optimization using dbt.", "tech_stack": ["Python", "AWS", "dbt", "Apache Spark", "SQL"], "difficulty": "Advanced", "time_weeks": 5},
        {"title": "Data Quality Framework", "description": "Build automated data quality checks with anomaly detection, data profiling, and alerting.", "tech_stack": ["Python", "Great Expectations", "Apache Airflow", "PostgreSQL"], "difficulty": "Intermediate", "time_weeks": 3},
    ],
    "DevOps Engineer": [
        {"title": "CI/CD Pipeline System", "description": "Build a complete CI/CD pipeline with automated testing, Docker builds, staging/production deployments, and rollbacks.", "tech_stack": ["Docker", "Kubernetes", "GitHub Actions", "Terraform", "Linux"], "difficulty": "Intermediate", "time_weeks": 3},
        {"title": "Infrastructure as Code Platform", "description": "Design multi-environment infrastructure with Terraform modules for VPC, compute, databases, and monitoring.", "tech_stack": ["Terraform", "AWS", "Docker", "Linux", "Bash/Shell"], "difficulty": "Advanced", "time_weeks": 4},
        {"title": "Monitoring & Alerting Stack", "description": "Set up a full observability stack with metrics, logs, traces, dashboards, and intelligent alerting.", "tech_stack": ["Docker", "Prometheus", "Grafana", "Linux", "Kubernetes"], "difficulty": "Intermediate", "time_weeks": 3},
        {"title": "GitOps Deployment System", "description": "Implement GitOps workflow using ArgoCD for automated Kubernetes deployments from Git repositories.", "tech_stack": ["Kubernetes", "Docker", "Git", "CI/CD", "Linux"], "difficulty": "Advanced", "time_weeks": 4},
    ],
    "Cloud Engineer": [
        {"title": "Serverless API Platform", "description": "Build a serverless REST API using AWS Lambda, API Gateway, and DynamoDB with infrastructure as code.", "tech_stack": ["AWS", "Terraform", "Python", "Docker", "CI/CD"], "difficulty": "Intermediate", "time_weeks": 3},
        {"title": "Multi-Region High Availability Setup", "description": "Design a multi-region, fault-tolerant application with automated failover, load balancing, and disaster recovery.", "tech_stack": ["AWS", "Terraform", "Docker", "Kubernetes", "Linux"], "difficulty": "Advanced", "time_weeks": 5},
        {"title": "Cost Optimization Dashboard", "description": "Build a cloud cost monitoring tool that tracks spending, identifies waste, and suggests optimizations.", "tech_stack": ["Python", "AWS", "Terraform", "Docker", "Linux"], "difficulty": "Intermediate", "time_weeks": 3},
    ],
    "Mobile Developer": [
        {"title": "Social Fitness App", "description": "Build a fitness tracking app with workout logging, social feed, challenges, and progress visualization.", "tech_stack": ["Flutter", "Dart", "Firebase", "REST APIs", "Git"], "difficulty": "Intermediate", "time_weeks": 4},
        {"title": "Expense Tracker with Analytics", "description": "Create a personal finance app with expense categorization, budget tracking, charts, and receipt scanning.", "tech_stack": ["React Native", "JavaScript", "Firebase", "REST APIs"], "difficulty": "Intermediate", "time_weeks": 3},
        {"title": "Real-Time Location Sharing", "description": "Build a location sharing app with real-time map updates, geofencing, and route tracking.", "tech_stack": ["Flutter", "Dart", "Google Maps API", "Firebase", "Git"], "difficulty": "Advanced", "time_weeks": 4},
    ],
    "Android Developer": [
        {"title": "News Aggregator App", "description": "Build a news app with offline reading, push notifications, bookmarks, and personalized recommendations.", "tech_stack": ["Kotlin", "Android Development", "REST APIs", "Room DB", "Git"], "difficulty": "Intermediate", "time_weeks": 3},
        {"title": "Smart Home Controller", "description": "Create an IoT dashboard to control smart devices with real-time status, scheduling, and automation.", "tech_stack": ["Kotlin", "Android Development", "Firebase", "REST APIs", "MQTT"], "difficulty": "Advanced", "time_weeks": 4},
    ],
    "iOS Developer": [
        {"title": "Health & Wellness Tracker", "description": "Build an iOS app integrating HealthKit for activity tracking, habit building, and health insights.", "tech_stack": ["Swift", "iOS Development", "HealthKit", "Core Data", "Git"], "difficulty": "Intermediate", "time_weeks": 3},
        {"title": "AR Shopping Experience", "description": "Create an augmented reality shopping app where users can preview furniture/products in their space.", "tech_stack": ["Swift", "iOS Development", "ARKit", "REST APIs", "Git"], "difficulty": "Advanced", "time_weeks": 5},
    ],
    "Database Administrator": [
        {"title": "Database Performance Analyzer", "description": "Build a tool to analyze slow queries, suggest indexing strategies, and monitor database health metrics.", "tech_stack": ["Python", "PostgreSQL", "SQL", "Linux", "Bash/Shell"], "difficulty": "Intermediate", "time_weeks": 3},
        {"title": "Automated Backup & Recovery System", "description": "Design an automated database backup system with point-in-time recovery, health checks, and alerting.", "tech_stack": ["PostgreSQL", "Linux", "Bash/Shell", "Docker", "Python"], "difficulty": "Advanced", "time_weeks": 4},
    ],
    "Security Engineer": [
        {"title": "Vulnerability Scanner", "description": "Build an automated vulnerability scanner for web applications covering OWASP Top 10 with reporting.", "tech_stack": ["Python", "Linux", "Docker", "Bash/Shell", "Git"], "difficulty": "Advanced", "time_weeks": 4},
        {"title": "SIEM Log Analyzer", "description": "Create a security event analysis tool with log parsing, threat detection rules, and incident alerting.", "tech_stack": ["Python", "Linux", "Docker", "Elasticsearch", "Bash/Shell"], "difficulty": "Advanced", "time_weeks": 5},
    ],
    "QA Engineer": [
        {"title": "Automated E2E Test Suite", "description": "Build a comprehensive end-to-end test framework with page objects, data factories, and CI integration.", "tech_stack": ["Selenium", "Python", "pytest", "Docker", "CI/CD"], "difficulty": "Intermediate", "time_weeks": 3},
        {"title": "API Testing Framework", "description": "Design a reusable API testing library with contract testing, load testing, and automated regression suites.", "tech_stack": ["Python", "pytest", "REST APIs", "Docker", "Git"], "difficulty": "Intermediate", "time_weeks": 2},
    ],
    "Tech Lead": [
        {"title": "Architecture Decision Records System", "description": "Build a tool for documenting and tracking architecture decisions with templates, search, and versioning.", "tech_stack": ["React", "Node.js", "PostgreSQL", "Git", "Docker"], "difficulty": "Intermediate", "time_weeks": 3},
        {"title": "Team Health Dashboard", "description": "Create a dashboard tracking team velocity, code quality metrics, deployment frequency, and tech debt.", "tech_stack": ["React", "Python", "REST APIs", "Git", "Docker"], "difficulty": "Intermediate", "time_weeks": 3},
    ],
}

# ---------------------------------------------------------------------------
# Resume improvement tips by category
# ---------------------------------------------------------------------------
RESUME_TIPS: dict[str, list[dict[str, str]]] = {
    "structure": [
        {"tip": "Keep your resume to 1-2 pages max", "detail": "Recruiters spend an average of 7 seconds scanning a resume. Keep it concise and impactful."},
        {"tip": "Use a clean, ATS-friendly format", "detail": "Avoid complex layouts, tables, or graphics that ATS systems can't parse. Stick to standard headings."},
        {"tip": "Order sections strategically", "detail": "Put your strongest section first. For students: Education → Projects → Skills. For experienced: Experience → Skills → Education."},
        {"tip": "Add a compelling summary/objective", "detail": "Start with a 2-3 line professional summary highlighting your target role, key skills, and value proposition."},
    ],
    "content": [
        {"tip": "Quantify your achievements", "detail": "Use numbers: 'Reduced API response time by 40%' is far more impactful than 'Improved API performance'."},
        {"tip": "Use strong action verbs", "detail": "Start each bullet with verbs like Developed, Architected, Optimized, Deployed, Spearheaded, Engineered."},
        {"tip": "Tailor to your target role", "detail": "Customize your skills section and project descriptions to match the job description keywords."},
        {"tip": "Include relevant certifications", "detail": "AWS, Google Cloud, Azure, or domain-specific certifications significantly boost your credibility."},
    ],
    "projects": [
        {"tip": "Showcase 2-3 impactful projects", "detail": "Quality over quantity. Each project should demonstrate problem-solving and technical depth."},
        {"tip": "Include links to live demos or GitHub", "detail": "Recruiters want to see your work. Add GitHub repos or deployed links for every project."},
        {"tip": "Describe the problem, solution, and impact", "detail": "Structure each project as: What problem did you solve? How? What was the measurable outcome?"},
        {"tip": "Use your target role's tech stack", "detail": "Build projects using technologies required for your desired role to prove hands-on experience."},
    ],
    "skills": [
        {"tip": "Group skills by category", "detail": "Organize as: Languages, Frameworks, Databases, Cloud, Tools — makes scanning easier for recruiters."},
        {"tip": "Remove outdated or irrelevant skills", "detail": "Don't list basic skills like MS Word or HTML if applying for ML/Backend roles. Focus on role-relevant skills."},
        {"tip": "Match keywords from job descriptions", "detail": "Many companies use ATS filters. Include exact skill names from the job description."},
    ],
}